# _config.yml

title: Tracks
description: UnExplored
baseurl: "/tracks"
url: "https://nulltalisman.github.io"

plugins:
  - jekyll-paginate-v2
  - jekyll-feed
  - jekyll-seo-tag

pagination:
  enabled: true
  per_page: 10
  permalink: /page/:num/
  title: ':title - page :num'
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2
